project_id = "ckgtwwtgutvgjqszhwvh"

[functions.mercadopago-create-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.validate-booking]
verify_jwt = false

[functions.check-premium-access]
verify_jwt = false